"""empty message

Revision ID: a7b839e703b3
Revises: 3f1cf25d4100
Create Date: 2020-10-26 17:36:38.179758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b839e703b3'
down_revision = '3f1cf25d4100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_id')
    # ### end Alembic commands ###
